cc_library(
  name = 'jpeg',
  export_incs = [
    'include'
  ],
  prebuilt = True,
  warning = 'no',
)

cc_library(
  name = 'turbojpeg',
  export_incs = [
    'include'
  ],
  prebuilt = True,
  warning = 'no',
)
